### ISSUE TITLE
Self-signed certificates instead of letsencrypt

### ISSUE THREAD

**Issue by daic11** [opencloud-eu/docs#169]
### Why need this?

My certificates with letsencrypt changes every time I reboot my server and I should accept them every time

### How to achieve this?

I this instruction I would use  certFile: /etc/ssl/tls.crt and keyFile: /etc/ssl/tls.key with the owner of this files by the user you start opencloud.

1. Remove the whole certificatesResolvers section here: https://github.com/opencloud-eu/opencloud/blob/43c3b814ccb42c60d5edc9f6debf4b3688e96331/deployments/examples/opencloud_full/docker-compose.yml#L11
2. Add extra volumes to the file mentioned in step 1:

```
command:
      - "--providers.file.filename=/dynamic.yml"
volumes:
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"
      - "certs:/certs"
      - "/etc/ssl/tls.crt:/etc/ssl/tls.crt:ro"
      - "/etc/ssl/tls.key:/etc/ssl/tls.key:ro"
      - "./dynamic.yml:/dynamic.yml"
labels:
     - "traefik.http.routers.traefik.tls=true"
```

The whole config could look like this:

```
services:
  traefik:
    image: traefik:v3.3.1
    # release notes: https://github.com/traefik/traefik/releases
    networks:
      opencloud-net:
      web:
      bank:
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # enable dashboard
      - "--api.dashboard=true"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # change default timeouts for long-running requests
      # this is needed for webdav clients that do not support the TUS protocol
      - "--entryPoints.https.transport.respondingTimeouts.readTimeout=12h"
      - "--entryPoints.https.transport.respondingTimeouts.writeTimeout=12h"
      - "--entryPoints.https.transport.respondingTimeouts.idleTimeout=3m"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      # access log
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.fields.headers.names.X-Request-Id=keep"
      - "--providers.file.filename=/dynamic.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"
      - "certs:/certs"
      - "/etc/ssl/tls.crt:/etc/ssl/tls.crt:ro"
      - "/etc/ssl/tls.key:/etc/ssl/tls.key:ro"
      - "./dynamic.yml:/dynamic.yml"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
       # defaults to admin:admin
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.opencloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  certs:

networks:
  opencloud-net:
  web: // I use this network for external services
```

Add dynamic.yml in same directory with docker-compose.yml:

```
tls:
  certificates:
    - certFile: /etc/ssl/tls.crt
      keyFile: /etc/ssl/tls.key

```

### Add external extra website to work with the current traefik config.

I've added docker web network for this `docker network create web`.

In the compose.yml of any docker application add this (gitea example):

```
    ports: // 7073 is an external port, 3000 internal inside web and private docker networks
      - 127.17.0.1:7073:3000
    networks:
      - web // for external connection with traefik
      - private // for in-app connection with database and other service
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.rule=Host(`git.cloud.su`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.services.gitea.loadbalancer.server.scheme=http"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea-http.rule=Host(`git.cloud.su`)"
      - "traefik.http.routers.gitea-http.entrypoints=http"
      - "traefik.http.routers.gitea-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
   extra_hosts:
      - "gitea-gitea-1:127.0.0.1"
  
// Add this for other services in this yml file to enable communication between them(web only for the main service above):
networks:
      - private
// Add at the end of this yml file to activate networks:
networks:
  web:
    external: true
  private:
```
